### ISSUE TITLE
Mental models for "agents"

### ISSUE THREAD

**Issue by benrito** [Tebs-Lab/LLMs-Non-Eng-Two-Day-Workshop#1]
re: https://github.com/Tebs-Lab/LLMs-Non-Eng-Two-Day-Workshop/blob/main/01-the-fundamentals/01-big-picture.md

Coupla thoughts:

1. there are lots of definitions for "AI agents" or "agentic AI" flying around (recursion? tool use? autonomy? etc). I'm not sure there's any one canonical definition. and the definitions straddle technical, symbolic, prescriptive — maybe it would be helpful to acknowledge and share some example definitions? 
3. related to above, for for a lot of folks, the distinction between an "agent" and "application" will still feel a bit unclear. e.g., you have applications made up of agents, agents that don't really qualify as applications, and also "agentic" applications. as before, maybe helpful to acknowledge some of the ambigtuity or offer some complimentary definitions?
4. last thing, in terms of examples — with the Apple event this week, Siri is getting a whole lot more "agentic" — and Siri's gonna benefit from a lot of system level AI goodness, so the analogy may not be as clean any more. maybe good to anticipate q's...

happy to help think through any of this!

**Comment by tebba-von-mathenstein** [comment]
Thanks!

Resolved in: https://github.com/Tebs-Lab/LLMs-Non-Eng-Two-Day-Workshop/commit/875aa83b4e02da9ad38c19ce2340f5a600660556

Added...

* A callout to Siri's recent/imminent evolution with Apple Intelligence. 
* Some bullets directly acknowledging the growing ambiguity around the definition of "agents" as well as the growing interplay and integration between "agents" and "applications"
