### ISSUE TITLE
Some potentially helpful material for 2e

### ISSUE THREAD

**Issue by benrito** [Tebs-Lab/LLMs-Non-Eng-Two-Day-Workshop#2]
Re: https://github.com/Tebs-Lab/LLMs-Non-Eng-Two-Day-Workshop/blob/main/01-the-fundamentals/02e-training-discussion-section.md

These are always crowd pleasers:

https://www.nytimes.com/interactive/2023/04/26/upshot/gpt-from-scratch.html

https://www.washingtonpost.com/technology/interactive/2023/ai-chatbot-learning/?pwapi_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJpZCI6IjM5MTA0ODQ2IiwicmVhc29uIjoiZ2lmdCIsIm5iZiI6MTY4MTg3NjgwMCwiaXNzIjoic3Vic2NyaXB0aW9ucyIsImV4cCI6MTY4MzE3Mjc5OSwiaWF0IjoxNjgxODc2ODAwLCJqdGkiOiI0ZDY5MWRjMy1kNDUwLTQzMjItOGM4Yi04ODdiYjI2YmE0ZDUiLCJ1cmwiOiJodHRwczovL3d3dy53YXNoaW5ndG9ucG9zdC5jb20vdGVjaG5vbG9neS9pbnRlcmFjdGl2ZS8yMDIzL2FpLWNoYXRib3QtbGVhcm5pbmcvIn0.5ZNpiRoYwaU629RoMJusW2rg_Ubx2i7r1wIBvEzBPZY&itid=gfta

**Comment by tebba-von-mathenstein** [comment]
Thanks! 

Resolved in [875aa83b4e02da9ad38c19ce2340f5a600660556](https://github.com/Tebs-Lab/LLMs-Non-Eng-Two-Day-Workshop/commit/875aa83b4e02da9ad38c19ce2340f5a600660556) 

Added the first to the first discussion exercise, as well as a list of some other popular datasets and brief descriptions of them.

Added the second to a mini-exercise in the second lecture section. Added the
